### ISSUE TITLE
Help with pin connection

### ISSUE THREAD

**Issue by joelstitch** [odwdinc/DWIN_T5UIC1_LCD#19]
DELETE

**Comment by joelstitch** [comment]
I followed the instructions very carefully but when I get to running the run.py I just get all these errors:

`DWIN handshake
Traceback (most recent call last):
  File "/home/pi/DWIN_T5UIC1_LCD/dwinlcd.py", line 2252, in encoder_has_data
    if self.checkkey == self.MainMenu:
AttributeError: 'DWIN_LCD' object has no attribute 'checkkey'
Traceback (most recent call last):
  File "/home/pi/DWIN_T5UIC1_LCD/dwinlcd.py", line 2252, in encoder_has_data
    if self.checkkey == self.MainMenu:
AttributeError: 'DWIN_LCD' object has no attribute 'checkkey'
Traceback (most recent call last):
  File "/home/pi/DWIN_T5UIC1_LCD/dwinlcd.py", line 2252, in encoder_has_data
    if self.checkkey == self.MainMenu:
AttributeError: 'DWIN_LCD' object has no attribute 'checkkey'
Traceback (most recent call last):
  File "/home/pi/DWIN_T5UIC1_LCD/dwinlcd.py", line 2252, in encoder_has_data
    if self.checkkey == self.MainMenu:
AttributeError: 'DWIN_LCD' object has no attribute 'checkkey'
Traceback (most recent call last):
  File "/home/pi/DWIN_T5UIC1_LCD/dwinlcd.py", line 2252, in encoder_has_data
    if self.checkkey == self.MainMenu:
AttributeError: 'DWIN_LCD' object has no attribute 'checkkey'
Traceback (most recent call last):
  File "/home/pi/DWIN_T5UIC1_LCD/dwinlcd.py", line 2252, in encoder_has_data
    if self.checkkey == self.MainMenu:
AttributeError: 'DWIN_LCD' object has no attribute 'checkkey'
Traceback (most recent call last):
  File "/home/pi/DWIN_T5UIC1_LCD/dwinlcd.py", line 2252, in encoder_has_data
    if self.checkkey == self.MainMenu:
`

Running it as sudo gives me the same errors. Any suggestions on what to do to fix this?

**Comment by Felos9001** [comment]
I am having the same issue,
I am running klipper on mainsailos and Moonraker. installed with kiuah.

```
python3 ./run.py

DWIN handshake
Traceback (most recent call last):
  File "/home/felos/DWIN_T5UIC1_LCD/encoder.py", line 38, in transitionOccurred
    self.callback(self.value)
  File "/home/felos/DWIN_T5UIC1_LCD/dwinlcd.py", line 2252, in encoder_has_data
    if self.checkkey == self.MainMenu:
AttributeError: 'DWIN_LCD' object has no attribute 'checkkey'
```
