### ISSUE TITLE
KeyError: 'job'

### ISSUE THREAD

**Issue by GalvanicGlaze** [odwdinc/DWIN_T5UIC1_LCD#5]
Hey, hoping you can help.

I did everything as per the list but getting stuck on an error

When I run the run.py file it stops on KeyError: 'job'. Here is a copy from putty:

pi@octopi:~/DWIN_T5UIC1_LCD $ python3 ./run.py

DWIN handshake
DWIN OK.
http://127.0.0.1:80
Waiting for connect to /tmp/klippy_uds

Connection.

Boot looks good
Testing Web-services
Web site exists
Traceback (most recent call last):
  File "./run.py", line 13, in <module>
    API_Key
  File "/home/pi/DWIN_T5UIC1_LCD/dwinlcd.py", line 322, in __init__
    self.pd.init_Webservices()
  File "/home/pi/DWIN_T5UIC1_LCD/printerInterface.py", line 355, in init_Webservices
    self.update_variable()
  File "/home/pi/DWIN_T5UIC1_LCD/printerInterface.py", line 400, in update_variable
    self.file_name = self.job_Info['job']['file']['name']
KeyError: 'job'

The screen is on with the Creality boot logo but nothing else.

Can you please give me same guidance

Setup:
Ender 3 v2
4.2.7 board
Rpi 4
Klipper with octoprint (dont know what moonraker is maybe i need this?)

**Comment by GalvanicGlaze** [comment]
Never mind, i added my API key and now its working 😅
